# Generated by Django 5.2.3 on 2025-07-02 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('hazirlaniyor', 'Hazırlanıyor'), ('gonderildi', 'Gönderildi'), ('teslim', 'Teslim Edildi')], default='hazirlaniyor', max_length=20),
        ),
    ]
